### ISSUE TITLE
Incorrect dedup results

### ISSUE THREAD

**Issue by mouradvt04** [rayyanqcri/rayyan-store#23] opened 2019-02-06 11:45 UTC
Rayyan-store said 1045 duplicates but showed only 45 in contrast RayyanSolr said 1055

refs: https://rayyan-staging.qcri.org/reviews/22 and https://rayyan.qcri.org/reviews/50479

**Comment by hammady** [comment] 2019-02-06 13:29
Duplicate of #18.

**Closed by hammady** 2019-02-06 13:29 UTC
Labels: duplicate
