### ISSUE TITLE
Importing zip files

### ISSUE THREAD

**Issue by mouradvt04** [rayyanqcri/rayyan-store#42] opened 2019-02-21 11:50 UTC
Importing zip files doesn't seem to work properly; this may not necessarily be a RayyanStore issue but the behavior is not the same in RayyanStore and RayyyanSolr
The tests were done in these two reviews:
https://rayyan-staging.qcri.org/reviews/33
https://rayyan.qcri.org/reviews/52580

"zbys.csv" was accepted but not "zbys.csv.zip"; it says “Error: Zip file has no supported entries. Entries must have one of the following extensions: bib, enw, gz, ris, docx, zip, ciw, xml, txt, csv [Zbys.csv.zip]” 
In RayyanSolr, it was able to read 1 entry and then returned an error “Error: Zip file has no supported entries. Entries must have one of the following extensions: bib, enw, gz, ris, docx, zip, ciw, xml, txt, csv [Zbys.csv.zip]” 
Same behavior with another file “Error: Zip file has no supported entries. Entries must have one of the following extensions: bib, enw, gz, ris, docx, zip, ciw, xml, txt, csv [6666.cleaned.txt.zip]”; in RayyanSolr it didn’t read any entry for this field 

For yet another file RayyanStore read 100 entries and returned an error “Error: Zip file has no supported entries. Entries must have one of the following extensions: bib, enw, gz, ris, docx, zip, ciw, xml, txt, csv [EmbaseCorrected.zip]	100/1,301”
RayyanSolr read more before returning an error "Error: Zip file has no supported entries. Entries must have one of the following extensions: bib, enw, gz, ris, docx, zip, ciw, xml, txt, csv [EmbaseCorrected.zip] | 691/1,301"

**Comment by hammady** [comment] 2019-02-24 06:22
@fabubaker We need to investigate to understand the relation with RayyanStore.

**Comment by fabubaker** [comment] 2019-02-24 06:40
@mouradvt04 Can you put the zip files on slack? 

Also, the bug is inconsistent, i.e. I can reproduce with Zbys.csv.zip but not with any of the other sample files I have, for eg: evidencelive15.ris.zip.

**Comment by fabubaker** [comment] 2019-02-24 10:38
After investigating, this bug seems to be more of a rayyan-formats issue than a RayyanStore one. 

The problem is that rayyan-formats does not properly detect encoding after .zip extraction, leading to errors like:

(in Solr):
```
>>>SQL<<< Permanent exception in scrape job 91: ActiveRecord::StatementInvalid:PG::CharacterNotInRepertoire: ERROR:  invalid byte sequence for encoding "UTF8": 0xa9
```

OR (in RayyanStore):

```
>>>SQL<<< Permanent exception in scrape job 87: Encoding::UndefinedConversionError:"\xEF" from ASCII-8BIT to UTF-8, backtrace: /usr/local/lib/ruby/2.3.0/json/common.rb:224:in `encode'
/usr/local/lib/ruby/2.3.0/json/common.rb:224:in `generate'
/usr/local/lib/ruby/2.3.0/json/common.rb:224:in `generate'
/usr/local/bundle/gems/rayyan-store-0.1.8/lib/rayyan-store.rb:242:in `post_request'
/usr/local/bundle/gems/rayyan-store-0.1.8/lib/rayyan-store.rb:27:in `import'
/home/app/models/scrape_job.rb:148:in `import_batch_for_rayyan_store'```
```

This is because rails is given the responsibility of char detection, which it only does for non-zip files.

There are two fixes:

1)  Push char detection to rayyan-formats, OR
2)  Perform char detection in rails for zipped files.

Moving this issue to a future milestone since it seems like a non-critical bug (have users complained?)

**Comment by mouradvt04** [comment] 2019-02-24 10:54
No complaints from users in RayyanSolr, but it's possible they think it's just one of those errors. 

What I don't understand is that how come it was able to read some entries in some of the cases in both RayyanSolr and RayyanStore. So in these cases, the files were unzipped.

**Comment by hammady** [comment] 2020-11-25 02:37
Duplicate of https://github.com/qcri/rayyan/issues/491

**Closed** 2020-11-25 02:38 UTC
